base: '%env(BASEURL)%'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: de_DE.utf8
    navigationTitle: English
    flag: us
    hreflang: ''
    websiteTitle: ''
rootPageId: 1
websiteTitle: ''
